// Constants for URL blocking, keywords, and boilerplate patterns

export const BLOCK_PATTERNS = [
  "/video",
  "/videos",
  "/live",
  "/liveblog",
  "/podcast",
  "/shop",
  "/store",
  "/tickets",
  "/about",
  "/contact",
  "/privacy",
  "/terms",
  "/login",
  "/signin",
  "/signup",
  "/account",
  "/ads",
  "/subscribe",
  "/newsletter",
  "/rss",
  "/feed",
  "/search",
  "/photo",
  "/gallery",
  ".pdf",
  ".jpg",
  ".jpeg",
  ".png",
  ".gif",
  ".zip",
  ".mp4",
  ".mp3",
] as const;

export const KEYWORDS = [
  "football",
  "soccer",
  "premier",
  "afcon",
  "fifa",
  "uefa",
  "champions",
  "goal",
  "transfer",
  "match",
  "fixture",
  "stats",
  "player",
] as const;

export const BOILERPLATE_PATTERNS = [
  "skip to content",
  "sign up",
  "sign in",
  "log in",
  "login",
  "register",
  "create account",
  "subscribe",
  "subscription",
  "unlock",
  "premium",
  "paywall",
  "trial",
  "try for",
  "buy now",
  "get access",
  "continue reading",
  "advertisement",
  "ad blocker",
  "sponsored",
  "promotion",
  "promoted",
  "notification",
  "push notification",
  "download the app",
  "get the app",
  "open in app",
  "cookie",
  "consent",
  "manage preferences",
  "privacy policy",
  "privacy",
  "terms",
  "terms of use",
  "all rights reserved",
  "copyright",
  "contact us",
  "about us",
  "help",
  "support",
  "language",
  "region",
  "edition",
  "select edition",
  "choose region",
  "back to top",
  "share",
  "print",
  "follow",
  "related topics",
  "related articles",
  "you might also like",
  "read more",
  "see more",
  "load more",
  "show more",
  "loading",
  "please wait",
  "no results",
  "not found",
  "oops",
  "we're having trouble",
  "temporarily unavailable",
  "live",
  "update",
  "match centre",
  "match center",
  "ft",
  "ht",
  "newsletter",
  "page not found",
  "sorry",
  "home",
] as const;

export const BBC_TEAM_PATH = "bbc.com/sport/football/teams/";

// Updated to 2024-25 Premier League teams
export const EPL_TEAM_SLUGS_ALL = [
  "arsenal",
  "aston-villa",
  "bournemouth",
  "brentford",
  "brighton-and-hove-albion",
  "chelsea",
  "crystal-palace",
  "everton",
  "fulham",
  "ipswich-town",
  "leicester-city",
  "liverpool",
  "manchester-city",
  "manchester-united",
  "newcastle-united",
  "nottingham-forest",
  "southampton",
  "tottenham-hotspur",
  "west-ham-united",
  "wolverhampton-wanderers",
] as const;
