// Football-related prompt suggestions

export const CONTEXT_PROMPTS = [
  "Who is the top scorer in the EPL right now?",
  "Which players have the most assists in the EPL this season?",
  "Which EPL team has the best defensive record so far?",
  "Which goalkeeper has the most clean sheets this season?",
  "Which club has the highest xG over the last five matches?",
  "Which team has the best recent form in the last five games?",
  "Who has created the most big chances in the EPL?",
  "Which midfielders lead progressive passes this season?",
  "Which strikers are outperforming their xG the most?",
  "Which attackers are underperforming their xG this season?",
  "How does Arsenal's home form compare to away form?",
  "How many goals has Liverpool scored from set pieces?",
  "Which EPL clubs have the strongest pressing metrics?",
  "Who were the top scorers in the latest AFCON tournament?",
  "What are the next AFCON fixtures this week?",
  "Which African national teams are in best form right now?",
  "Who are the standout players in the CAF Champions League?",
  "What are the latest results in the Egyptian Premier League?",
  "Which players are top scorers in the Moroccan Botola Pro?",
  "Which African players are performing best in Europe this season?",
  "What are Manchester City's next three matches?",
  "What are Chelsea's current injury concerns and return windows?",
  "What is Tottenham's likely lineup for the next match?",
  "Summarize Manchester United's last five results.",
  "Which clubs are leading the EPL title race right now?",
  "Which teams are most at risk in the relegation battle?",
  "Who are the best U21 performers in the EPL this season?",
  "Which players have the most yellow cards this season?",
  "Who leads the league in successful dribbles?",
  "Which team has the best chance-conversion rate?",
  "Which teams are strongest in second-half performances?",
  "Which clubs have scored the most goals from corners?",
  "Which teams are most likely to keep clean sheets this weekend?",
  "What is the most likely upset result this weekend?",
  "Compare Mohamed Salah and Erling Haaland this season.",
  "Which teams have the toughest upcoming fixture run?",
  "Which teams have the easiest upcoming fixture run?",
  "Who are the top scorers in La Liga this season?",
  "Which teams are leading the Serie A title race?",
  "Which Bundesliga side has the best attack this season?",
  "Which Ligue 1 teams have improved most this month?",
  "Who has the most assists in Serie A right now?",
  "Which Bundesliga players create the most chances?",
  "What are the biggest Champions League fixtures this week?",
  "Which teams are favorites to win the UEFA Champions League?",
  "Who are the top scorers in the UEFA Champions League?",
  "Who are the breakout players in the UEFA Conference League?",
  "How do Real Madrid and Barcelona compare this season?",
  "How do Inter Milan and Juventus compare this season?",
  "What are the biggest football transfer rumors right now?",
] as const;
